---
- name: setup vpc
  hosts: localhost
  gather_facts: true
  sudo_user: false
  pre_tasks:
    - include_vars: ../vars/vpc.yml
  tasks:
    - name: create VPC with public and private subnet
      ec2_vpc:
        state: present
        cidr_block: '{{ cidr }}'
        resource_tags: { "Environment":"Development" }
        subnets:
          - cidr: '{{ public_subnet }}'
            az: '{{ public_subnet_az }}'
            resource_tags: { "Subnet":"Public" }
          - cidr: '{{ private_subnet }}'
            az: '{{ private_subnet_az }}'
            resource_tags: { "Subnet":"Private" }
        internet_gateway: True
        route_tables:
          - subnets:
              - '{{ public_subnet }}'
            routes:
              - dest: 0.0.0.0/0
                gw: igw
          - subnets:
              - '{{ private_subnet }}'
            routes:
              - dest: 0.0.0.0/0
                gw: igw
        region: '{{ default_aws_region }}'
      register: vpc

- name: setup nat gateway
  hosts: localhost
  roles:
    - nat-gateway

- name: Change the route for VPC Private Subnet
  hosts: localhost
  gather_facts: true
  sudo_user: false
  pre_tasks:
    - include_vars: ../vars/vpc.yml

  tasks:
    - name: Modify private subnet
      ec2_vpc_route_table:
        vpc_id: '{{ vpc.vpc_id }}'
        region: '{{ default_aws_region }}'
        subnets:
          - "{{ lookup('file', '/tmp/private-subnet') }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ lookup('file', '/tmp/nat-gateway') }}"
